// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: api/webnavigation/navi.proto

package webnavigation

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNaviRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 分类名称
}

func (x *CreateNaviRequest) Reset() {
	*x = CreateNaviRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNaviRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNaviRequest) ProtoMessage() {}

func (x *CreateNaviRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNaviRequest.ProtoReflect.Descriptor instead.
func (*CreateNaviRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNaviRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateNaviReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 分类名称
}

func (x *CreateNaviReply) Reset() {
	*x = CreateNaviReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNaviReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNaviReply) ProtoMessage() {}

func (x *CreateNaviReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNaviReply.ProtoReflect.Descriptor instead.
func (*CreateNaviReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNaviReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NaviType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // 分类名称
	Index int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 排序序号，按照程序下标的规则，第一个的序号是0
}

func (x *NaviType) Reset() {
	*x = NaviType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NaviType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NaviType) ProtoMessage() {}

func (x *NaviType) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NaviType.ProtoReflect.Descriptor instead.
func (*NaviType) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{2}
}

func (x *NaviType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NaviType) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeleteNaviRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // 删除分类名称
	Force bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // 假如设置为false，假如分类下有东西就不能删除，假如设置为true就删除分类以及下面的东西
}

func (x *DeleteNaviRequest) Reset() {
	*x = DeleteNaviRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNaviRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNaviRequest) ProtoMessage() {}

func (x *DeleteNaviRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNaviRequest.ProtoReflect.Descriptor instead.
func (*DeleteNaviRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNaviRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteNaviRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteNaviReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNaviReply) Reset() {
	*x = DeleteNaviReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNaviReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNaviReply) ProtoMessage() {}

func (x *DeleteNaviReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNaviReply.ProtoReflect.Descriptor instead.
func (*DeleteNaviReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{4}
}

type SortNaviRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"` // 把分类名称按想要的顺序完整的传过来
}

func (x *SortNaviRequest) Reset() {
	*x = SortNaviRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortNaviRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortNaviRequest) ProtoMessage() {}

func (x *SortNaviRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortNaviRequest.ProtoReflect.Descriptor instead.
func (*SortNaviRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{5}
}

func (x *SortNaviRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SortNaviReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SortNaviReply) Reset() {
	*x = SortNaviReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortNaviReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortNaviReply) ProtoMessage() {}

func (x *SortNaviReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortNaviReply.ProtoReflect.Descriptor instead.
func (*SortNaviReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{6}
}

type NaviLvl2Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NaviName string `protobuf:"bytes,1,opt,name=navi_name,json=naviName,proto3" json:"navi_name,omitempty"`  // 分类名称
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                          // 名称：按钮上的简洁文字
	Text     string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                          // 中转页面内容部分包含以下元素 文案：后台自定义，比如“这是汇旺担保群，点击直达：”，文案单独一行；
	Link     string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`                          // 中转页面内容部分包含以下元素 链接：后台自定义链接文案，自定义链接的地址；字号比前面一行大两号；
	IsEscrow bool   `protobuf:"varint,5,opt,name=is_escrow,json=isEscrow,proto3" json:"is_escrow,omitempty"` // 需求-添加分类内容时可以勾选担保标志
	Index    int32  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`                       // 当前序号
}

func (x *NaviLvl2Item) Reset() {
	*x = NaviLvl2Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NaviLvl2Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NaviLvl2Item) ProtoMessage() {}

func (x *NaviLvl2Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NaviLvl2Item.ProtoReflect.Descriptor instead.
func (*NaviLvl2Item) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{7}
}

func (x *NaviLvl2Item) GetNaviName() string {
	if x != nil {
		return x.NaviName
	}
	return ""
}

func (x *NaviLvl2Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NaviLvl2Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NaviLvl2Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *NaviLvl2Item) GetIsEscrow() bool {
	if x != nil {
		return x.IsEscrow
	}
	return false
}

func (x *NaviLvl2Item) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type NaviListItemType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Navi      *NaviType       `protobuf:"bytes,1,opt,name=navi,proto3" json:"navi,omitempty"`
	NaviLvl2S []*NaviLvl2Item `protobuf:"bytes,2,rep,name=navi_lvl2s,json=naviLvl2s,proto3" json:"navi_lvl2s,omitempty"` // 2级菜单是有序的
}

func (x *NaviListItemType) Reset() {
	*x = NaviListItemType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NaviListItemType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NaviListItemType) ProtoMessage() {}

func (x *NaviListItemType) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NaviListItemType.ProtoReflect.Descriptor instead.
func (*NaviListItemType) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{8}
}

func (x *NaviListItemType) GetNavi() *NaviType {
	if x != nil {
		return x.Navi
	}
	return nil
}

func (x *NaviListItemType) GetNaviLvl2S() []*NaviLvl2Item {
	if x != nil {
		return x.NaviLvl2S
	}
	return nil
}

type ListNaviRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNaviRequest) Reset() {
	*x = ListNaviRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNaviRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNaviRequest) ProtoMessage() {}

func (x *ListNaviRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNaviRequest.ProtoReflect.Descriptor instead.
func (*ListNaviRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{9}
}

type ListNaviReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*NaviListItemType `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 1级菜单是有序的
}

func (x *ListNaviReply) Reset() {
	*x = ListNaviReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNaviReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNaviReply) ProtoMessage() {}

func (x *ListNaviReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNaviReply.ProtoReflect.Descriptor instead.
func (*ListNaviReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{10}
}

func (x *ListNaviReply) GetItems() []*NaviListItemType {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetGuestSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGuestSettingsRequest) Reset() {
	*x = GetGuestSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestSettingsRequest) ProtoMessage() {}

func (x *GetGuestSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetGuestSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{11}
}

type GetGuestSettingsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsNotRemindInfo bool `protobuf:"varint,1,opt,name=is_not_remind_info,json=isNotRemindInfo,proto3" json:"is_not_remind_info,omitempty"` ////根据cookie和IP判断，是否首次登陆
}

func (x *GetGuestSettingsReply) Reset() {
	*x = GetGuestSettingsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuestSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuestSettingsReply) ProtoMessage() {}

func (x *GetGuestSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuestSettingsReply.ProtoReflect.Descriptor instead.
func (*GetGuestSettingsReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{12}
}

func (x *GetGuestSettingsReply) GetIsNotRemindInfo() bool {
	if x != nil {
		return x.IsNotRemindInfo
	}
	return false
}

type SetNotRemindInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNotRemindInfoRequest) Reset() {
	*x = SetNotRemindInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNotRemindInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNotRemindInfoRequest) ProtoMessage() {}

func (x *SetNotRemindInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNotRemindInfoRequest.ProtoReflect.Descriptor instead.
func (*SetNotRemindInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{13}
}

type SetNotRemindInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNotRemindInfoReply) Reset() {
	*x = SetNotRemindInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_webnavigation_navi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNotRemindInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNotRemindInfoReply) ProtoMessage() {}

func (x *SetNotRemindInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_webnavigation_navi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNotRemindInfoReply.ProtoReflect.Descriptor instead.
func (*SetNotRemindInfoReply) Descriptor() ([]byte, []int) {
	return file_api_webnavigation_navi_proto_rawDescGZIP(), []int{14}
}

var File_api_webnavigation_navi_proto protoreflect.FileDescriptor

var file_api_webnavigation_navi_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x34, 0x0a, 0x08, 0x4e, 0x61, 0x76, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x0a, 0x0f, 0x53, 0x6f,
	0x72, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x9a, 0x01, 0x0a, 0x0c, 0x4e, 0x61, 0x76, 0x69, 0x4c, 0x76, 0x6c,
	0x32, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x61, 0x76, 0x69, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x76, 0x69, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x83, 0x01, 0x0a, 0x10, 0x4e, 0x61, 0x76, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6e, 0x61, 0x76, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61,
	0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x61, 0x76, 0x69, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x6e, 0x61, 0x76, 0x69, 0x12, 0x3e, 0x0a, 0x0a, 0x6e, 0x61, 0x76, 0x69, 0x5f,
	0x6c, 0x76, 0x6c, 0x32, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4e, 0x61, 0x76, 0x69, 0x4c, 0x76, 0x6c, 0x32, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6e, 0x61,
	0x76, 0x69, 0x4c, 0x76, 0x6c, 0x32, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4e,
	0x61, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e,
	0x61, 0x76, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x12, 0x69, 0x73,
	0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x4e, 0x6f,
	0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd1, 0x06, 0x0a, 0x04,
	0x4e, 0x61, 0x76, 0x69, 0x12, 0x85, 0x01, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x61, 0x76, 0x69, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61,
	0x76, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x27, 0x3a, 0x01, 0x2a, 0x22, 0x22, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77,
	0x65, 0x62, 0x2d, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x76, 0x69, 0x12, 0x85, 0x01, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69, 0x12, 0x24, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x69,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x3a, 0x01, 0x2a,
	0x22, 0x22, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2d, 0x6e, 0x61, 0x76, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x6e, 0x61, 0x76, 0x69, 0x12, 0x7d, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x76, 0x69,
	0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61,
	0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x76,
	0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x3a, 0x01,
	0x2a, 0x22, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2d, 0x6e, 0x61, 0x76, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6e,
	0x61, 0x76, 0x69, 0x12, 0x7a, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x76, 0x69,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x12, 0x20, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2d, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x76, 0x69, 0x12,
	0x9b, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61,
	0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2b, 0x12, 0x29, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2d, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x9f, 0x01,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x35, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2f,
	0x3a, 0x01, 0x2a, 0x22, 0x2a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2d, 0x6e, 0x61,
	0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74, 0x5f,
	0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x42,
	0x4d, 0x0a, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a, 0x36, 0x68, 0x75, 0x69, 0x2d, 0x77, 0x65, 0x62, 0x70,
	0x61, 0x67, 0x65, 0x2d, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x3b, 0x77, 0x65, 0x62, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_webnavigation_navi_proto_rawDescOnce sync.Once
	file_api_webnavigation_navi_proto_rawDescData = file_api_webnavigation_navi_proto_rawDesc
)

func file_api_webnavigation_navi_proto_rawDescGZIP() []byte {
	file_api_webnavigation_navi_proto_rawDescOnce.Do(func() {
		file_api_webnavigation_navi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_webnavigation_navi_proto_rawDescData)
	})
	return file_api_webnavigation_navi_proto_rawDescData
}

var file_api_webnavigation_navi_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_webnavigation_navi_proto_goTypes = []interface{}{
	(*CreateNaviRequest)(nil),       // 0: api.webnavigation.CreateNaviRequest
	(*CreateNaviReply)(nil),         // 1: api.webnavigation.CreateNaviReply
	(*NaviType)(nil),                // 2: api.webnavigation.NaviType
	(*DeleteNaviRequest)(nil),       // 3: api.webnavigation.DeleteNaviRequest
	(*DeleteNaviReply)(nil),         // 4: api.webnavigation.DeleteNaviReply
	(*SortNaviRequest)(nil),         // 5: api.webnavigation.SortNaviRequest
	(*SortNaviReply)(nil),           // 6: api.webnavigation.SortNaviReply
	(*NaviLvl2Item)(nil),            // 7: api.webnavigation.NaviLvl2Item
	(*NaviListItemType)(nil),        // 8: api.webnavigation.NaviListItemType
	(*ListNaviRequest)(nil),         // 9: api.webnavigation.ListNaviRequest
	(*ListNaviReply)(nil),           // 10: api.webnavigation.ListNaviReply
	(*GetGuestSettingsRequest)(nil), // 11: api.webnavigation.GetGuestSettingsRequest
	(*GetGuestSettingsReply)(nil),   // 12: api.webnavigation.GetGuestSettingsReply
	(*SetNotRemindInfoRequest)(nil), // 13: api.webnavigation.SetNotRemindInfoRequest
	(*SetNotRemindInfoReply)(nil),   // 14: api.webnavigation.SetNotRemindInfoReply
}
var file_api_webnavigation_navi_proto_depIdxs = []int32{
	2,  // 0: api.webnavigation.NaviListItemType.navi:type_name -> api.webnavigation.NaviType
	7,  // 1: api.webnavigation.NaviListItemType.navi_lvl2s:type_name -> api.webnavigation.NaviLvl2Item
	8,  // 2: api.webnavigation.ListNaviReply.items:type_name -> api.webnavigation.NaviListItemType
	0,  // 3: api.webnavigation.Navi.CreateNavi:input_type -> api.webnavigation.CreateNaviRequest
	3,  // 4: api.webnavigation.Navi.DeleteNavi:input_type -> api.webnavigation.DeleteNaviRequest
	5,  // 5: api.webnavigation.Navi.SortNavi:input_type -> api.webnavigation.SortNaviRequest
	9,  // 6: api.webnavigation.Navi.ListNavi:input_type -> api.webnavigation.ListNaviRequest
	11, // 7: api.webnavigation.Navi.GetGuestSettings:input_type -> api.webnavigation.GetGuestSettingsRequest
	13, // 8: api.webnavigation.Navi.SetNotRemindInfo:input_type -> api.webnavigation.SetNotRemindInfoRequest
	1,  // 9: api.webnavigation.Navi.CreateNavi:output_type -> api.webnavigation.CreateNaviReply
	4,  // 10: api.webnavigation.Navi.DeleteNavi:output_type -> api.webnavigation.DeleteNaviReply
	6,  // 11: api.webnavigation.Navi.SortNavi:output_type -> api.webnavigation.SortNaviReply
	10, // 12: api.webnavigation.Navi.ListNavi:output_type -> api.webnavigation.ListNaviReply
	12, // 13: api.webnavigation.Navi.GetGuestSettings:output_type -> api.webnavigation.GetGuestSettingsReply
	14, // 14: api.webnavigation.Navi.SetNotRemindInfo:output_type -> api.webnavigation.SetNotRemindInfoReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_webnavigation_navi_proto_init() }
func file_api_webnavigation_navi_proto_init() {
	if File_api_webnavigation_navi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_webnavigation_navi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNaviRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNaviReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NaviType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNaviRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNaviReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortNaviRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortNaviReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NaviLvl2Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NaviListItemType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNaviRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNaviReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuestSettingsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNotRemindInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_webnavigation_navi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNotRemindInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_webnavigation_navi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_webnavigation_navi_proto_goTypes,
		DependencyIndexes: file_api_webnavigation_navi_proto_depIdxs,
		MessageInfos:      file_api_webnavigation_navi_proto_msgTypes,
	}.Build()
	File_api_webnavigation_navi_proto = out.File
	file_api_webnavigation_navi_proto_rawDesc = nil
	file_api_webnavigation_navi_proto_goTypes = nil
	file_api_webnavigation_navi_proto_depIdxs = nil
}
