server:
  http:
    addr: 0.0.0.0:38000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:39000
    timeout: 10s
data:
  database:
    driver: mysql
    source: "root:123456@tcp(host.docker.internal:3306)/HuiWebpageNavigation?charset=utf8mb4&parseTime=True&loc=Local"
    echo: true
  anonymous_token: "abc"
