server:
  http:
    addr: 0.0.0.0:38000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:39000
    timeout: 10s
data:
  database:
    driver: mysql
    source: "root:123456@tcp(host.docker.internal:3306)/HuiWebpageNavigation?charset=utf8mb4&parseTime=True&loc=Local"
    echo: true
  auth:
    enable: true
    key: "Authorization"
    tokens: # map key:username value:token
      "ADMIN_123": "123"
      "ADMIN_abc": "abc"
      "ADMIN_XXX": "80f59c14b161429b88d9068d8cddca32"
